/* Signed-in student experience and lightweight engagement tracking. */
let portalUser = null;
const portalStartedAt = Date.now();
async function portalApi(url, options = {}) {const response = await fetch(url, { ...options, headers:{ 'Content-Type':'application/json', ...(options.headers || {}) } });if (response.status === 401) { window.location.href = '/login'; throw new Error('Please sign in.'); }const data = await response.json();if (!response.ok) throw new Error(data.error || 'Request failed.');return data;}
function sendEngagement(event, durationSeconds = 0) {const page = typeof getCurrentPortalPage === 'function' ? getCurrentPortalPage() : 'home';const body = JSON.stringify({ page, event, durationSeconds });if (navigator.sendBeacon && event === 'time_spent') navigator.sendBeacon('/api/engagement', new Blob([body], { type:'application/json' }));else fetch('/api/engagement', { method:'POST', headers:{'Content-Type':'application/json'}, body, keepalive:true }).catch(() => {});}
function applyAssignedTeamBranding() {if (portalUser.role !== 'student') return;const team = typeof getNFLTeamBrand === 'function' ? getNFLTeamBrand(portalUser.selectedTeam) : null;const primary=team?.primary||'#013369',secondary=team?.secondary||'#D50A0A';const style=document.createElement('style');style.textContent=`:root{--student-team-primary:${primary};--student-team-secondary:${secondary}}body:before{content:'';position:fixed;z-index:60;top:0;left:0;right:0;height:3px;background:var(--student-team-secondary)}nav{border-bottom-color:${primary}!important}nav [aria-current="page"]{background:${primary}33!important;border-color:${secondary}88!important;color:#fff!important}.student-team-mark{background:${primary};border:1px solid ${secondary};color:#fff}.student-team-accent{border-color:${secondary}!important}`;document.head.appendChild(style);const brand=document.querySelector('nav > div:first-child');if(brand&&team){const originalLogo=brand.querySelector('img');if(originalLogo){originalLogo.src=team.logo;originalLogo.alt=`${team.name} logo`;originalLogo.title=team.name;originalLogo.className='h-9 w-9 object-contain shrink-0';originalLogo.onerror=()=>{originalLogo.style.display='none'}}}}
function addAccountControls() {const nav = document.querySelector('nav');const right = nav?.lastElementChild;if (!right || document.getElementById('account-controls')) return;const controls = document.createElement('div');controls.id = 'account-controls';controls.className = 'shrink-0 flex items-center gap-2';controls.innerHTML = `${portalUser.role === 'teacher' ? '<a href="/teacher" title="Teacher dashboard" class="w-8 h-8 rounded-lg bg-white/5 flex items-center justify-center"><iconify-icon icon="lucide:layout-dashboard"></iconify-icon></a>' : ''}<span class="hidden xl:inline text-[10px] text-white/45 max-w-[90px] truncate">${portalUser.displayName}</span><button id="portal-logout" title="Sign out" class="w-8 h-8 rounded-lg bg-white/5 flex items-center justify-center hover:bg-red-500/15 hover:text-red-300"><iconify-icon icon="lucide:log-out"></iconify-icon></button>`;right.appendChild(controls);controls.querySelector('#portal-logout').addEventListener('click', async () => { await portalApi('/api/logout', { method:'POST' }); window.location.href='/login'; });}
async function initializeAccountExperience() {try {const { user } = await portalApi('/api/me');portalUser = user;applyAssignedTeamBranding(); addAccountControls(); sendEngagement('page_view');} catch (error) { console.warn('Account experience could not initialize.', error); }}
window.addEventListener('pagehide', () => sendEngagement('time_spent', Math.round((Date.now() - portalStartedAt) / 1000)));
initializeAccountExperience();
