const crypto=require('crypto');
const TEAM_NAMES={ARI:'Arizona Cardinals',ATL:'Atlanta Falcons',BAL:'Baltimore Ravens',BUF:'Buffalo Bills',CAR:'Carolina Panthers',CHI:'Chicago Bears',CIN:'Cincinnati Bengals',CLE:'Cleveland Browns',DAL:'Dallas Cowboys',DEN:'Denver Broncos',DET:'Detroit Lions',GB:'Green Bay Packers',HOU:'Houston Texans',IND:'Indianapolis Colts',JAX:'Jacksonville Jaguars',KC:'Kansas City Chiefs',LV:'Las Vegas Raiders',LAC:'Los Angeles Chargers',LAR:'Los Angeles Rams',MIA:'Miami Dolphins',MIN:'Minnesota Vikings',NE:'New England Patriots',NO:'New Orleans Saints',NYG:'New York Giants',NYJ:'New York Jets',PHI:'Philadelphia Eagles',PIT:'Pittsburgh Steelers',SF:'San Francisco 49ers',SEA:'Seattle Seahawks',TB:'Tampa Bay Buccaneers',TEN:'Tennessee Titans',WAS:'Washington Commanders'};
const pick=values=>values[Math.floor(Math.random()*values.length)];
async function initCoach(pool){await pool.query(`CREATE TABLE IF NOT EXISTS coach_challenges(id VARCHAR(64) PRIMARY KEY,user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,question TEXT NOT NULL,answer VARCHAR(80) NOT NULL,explanation TEXT NOT NULL,xp INTEGER NOT NULL DEFAULT 5,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),answered_at TIMESTAMPTZ);CREATE TABLE IF NOT EXISTS coach_question_log(id BIGSERIAL PRIMARY KEY,user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,page VARCHAR(32) NOT NULL,question TEXT NOT NULL,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());ALTER TABLE coach_question_log ALTER COLUMN user_id DROP NOT NULL;CREATE INDEX IF NOT EXISTS coach_question_created_idx ON coach_question_log(created_at DESC);`)}
function challengeFor(user){const team=TEAM_NAMES[user.selected_team];const general=[{question:'How many teams are in the NFL?',answer:'32',explanation:'The NFL has 32 teams.'},{question:'How many conferences are in the NFL?',answer:'2',explanation:'The NFL has two conferences: the AFC and NFC.'},{question:'How many yards long is the football field between the goal lines?',answer:'100',explanation:'The field is 100 yards from goal line to goal line.'},{question:'How many points is a touchdown worth?',answer:'6',explanation:'A touchdown is worth 6 points.'}];if(team)general.push({question:`What is the abbreviation for your team, the ${team}?`,answer:user.selected_team,explanation:`The ${team} use the abbreviation ${user.selected_team}.`});return pick(general)}
const normalize=value=>String(value??'').trim().toLowerCase().replace(/[^a-z0-9]/g,'');
async function handleCoach({pool,req,res,path,user,sendJson,readJson}){
  if(!path.startsWith('/api/coach/'))return false;if(!user){sendJson(res,401,{error:'Please sign in.'});return true}
  if(path==='/api/coach/context'&&req.method==='GET'){const setting=(await pool.query("SELECT setting_value FROM classroom_settings WHERE setting_key='coach_focus'")).rows[0]?.setting_value||null;sendJson(res,200,{focus:setting,assignedTeam:user.selected_team||null});return true}
  if(path==='/api/coach/focus'&&req.method==='PATCH'){if(user.role!=='teacher'){sendJson(res,403,{error:'Teacher access required.'});return true}const body=await readJson(req),focus={prompt:String(body.prompt||'').trim().slice(0,500)};await pool.query("INSERT INTO classroom_settings(setting_key,setting_value,updated_by) VALUES('coach_focus',$1,$2) ON CONFLICT(setting_key) DO UPDATE SET setting_value=EXCLUDED.setting_value,updated_by=EXCLUDED.updated_by,updated_at=NOW()",[focus,user.id]);sendJson(res,200,{focus});return true}
  if(path==='/api/coach/questions'&&req.method==='GET'){if(user.role!=='teacher'){sendJson(res,403,{error:'Teacher access required.'});return true}const questions=(await pool.query(`SELECT question,COUNT(*)::int AS count,MAX(created_at) AS last_asked FROM coach_question_log WHERE created_at>NOW()-INTERVAL '30 days' GROUP BY question ORDER BY count DESC,last_asked DESC LIMIT 10`)).rows;sendJson(res,200,{questions});return true}
  if(path==='/api/coach/log'&&req.method==='POST'){const body=await readJson(req),question=String(body.question||'').trim().slice(0,240);if(question)await pool.query('INSERT INTO coach_question_log(page,question) VALUES($1,$2)',[String(body.page||'home').slice(0,32),question]);sendJson(res,201,{ok:true});return true}
  if(path==='/api/coach/challenge'&&req.method==='POST'){await pool.query('DELETE FROM coach_challenges WHERE user_id=$1 AND answered_at IS NULL',[user.id]);const challenge=challengeFor(user),id=crypto.randomBytes(20).toString('hex');await pool.query('INSERT INTO coach_challenges(id,user_id,question,answer,explanation) VALUES($1,$2,$3,$4,$5)',[id,user.id,challenge.question,challenge.answer,challenge.explanation]);sendJson(res,201,{challenge:{id,question:challenge.question,xp:5}});return true}
  if(path==='/api/coach/answer'&&req.method==='POST'){const body=await readJson(req),result=await pool.query('UPDATE coach_challenges SET answered_at=NOW() WHERE id=$1 AND user_id=$2 AND answered_at IS NULL RETURNING *',[String(body.challengeId||''),user.id]),challenge=result.rows[0];if(!challenge){sendJson(res,404,{error:'That coach challenge is no longer active.'});return true}const correct=normalize(body.answer)===normalize(challenge.answer),xp=correct?challenge.xp:0;await pool.query('INSERT INTO math_profiles(user_id) VALUES($1) ON CONFLICT DO NOTHING',[user.id]);if(correct){await pool.query('UPDATE math_profiles SET total_xp=total_xp+$2,updated_at=NOW() WHERE user_id=$1',[user.id,xp]);await pool.query(`INSERT INTO math_weekly_stats(user_id,week_start,xp) VALUES($1,date_trunc('week',CURRENT_DATE)::date,$2) ON CONFLICT(user_id,week_start) DO UPDATE SET xp=math_weekly_stats.xp+EXCLUDED.xp`,[user.id,xp])}sendJson(res,200,{correct,xpEarned:xp,correctAnswer:challenge.answer,explanation:challenge.explanation});return true}
  sendJson(res,404,{error:'Coach endpoint not found.'});return true
}
module.exports={initCoach,handleCoach};
