/* Page navigation for the NFL classroom portal.
   Each page keeps the shared data engine in index.html, but only shows the selected classroom section. */
const PORTAL_PAGES=[{id:'home',label:'Home'},{id:'dashboard',label:'My Dashboard'},{id:'teams',label:'Teams'},{id:'matchups',label:'Matchups'},{id:'stats',label:'Team Stats'},{id:'players',label:'Player Stats'},{id:'travel',label:'Travel'},{id:'math',label:'Math Lab'},{id:'writing',label:'Writing'},{id:'cities',label:'Cities & States'},{id:'tcu',label:'TCU'}];
function portalPageUrl(id){return id==='home'?'index.html':`index.html?page=${id}`}
function getCurrentPortalPage(){const requested=new URLSearchParams(window.location.search).get('page');return PORTAL_PAGES.some(page=>page.id===requested)?requested:'home'}
function prepareDashboardSection(){const section=document.getElementById('facts');if(section){section.id='dashboard';section.className='py-24 px-4 md:px-6 section-reveal'}}
function showCurrentPortalPage(id){document.querySelectorAll('body > section').forEach(section=>{const sid=section.id?section.id.toLowerCase():'home';const show=id==='home'&&(!section.id||section.id==='featured')||sid===id;section.style.display=show?'':'none';if(show)section.classList.add('visible')});document.title=`${PORTAL_PAGES.find(page=>page.id===id).label} | NFL Project Student Portal`}
function rewritePortalLinks(){document.querySelectorAll('a[href^="#"]').forEach(link=>{const target=link.getAttribute('href').slice(1).toLowerCase();if(target==='facts'){link.href=portalPageUrl('dashboard');link.textContent='My Dashboard'}else if(PORTAL_PAGES.some(page=>page.id===target))link.href=portalPageUrl(target)})}
function buildPortalTopNavigation(id){const nav=document.querySelector('nav');if(!nav)return;const brand=nav.firstElementChild,right=nav.lastElementChild;if(!brand||!right)return;const old=right.firstElementChild;if(old)old.style.display='none';nav.classList.add('gap-3');brand.classList.add('shrink-0');right.classList.add('flex-1','min-w-0','justify-end');const menu=document.createElement('div');menu.className='flex-1 min-w-0 overflow-x-auto';menu.setAttribute('aria-label','Main pages');menu.style.scrollbarWidth='none';menu.innerHTML=`<div class="flex items-center justify-start lg:justify-end gap-1 min-w-max px-1">${PORTAL_PAGES.map(page=>`<a href="${portalPageUrl(page.id)}"${page.id===id?' aria-current="page"':''} class="whitespace-nowrap px-3 py-2 rounded-lg text-[11px] font-medium transition ${page.id===id?'bg-brand-500/20 text-brand-400 border border-brand-500/30':'text-white/55 border border-transparent hover:text-white hover:bg-white/5'}">${page.label}</a>`).join('')}</div>`;right.prepend(menu);menu.querySelector('[aria-current="page"]')?.scrollIntoView({block:'nearest',inline:'center'});brand.setAttribute('role','link');brand.setAttribute('tabindex','0');brand.setAttribute('aria-label','Go to home page');brand.style.cursor='pointer';brand.addEventListener('click',()=>window.location.href=portalPageUrl('home'));brand.addEventListener('keydown',event=>{if(event.key==='Enter'||event.key===' ')window.location.href=portalPageUrl('home')})}
function addPageFooterNavigation(id){const footer=document.querySelector('footer');if(!footer)return;const index=PORTAL_PAGES.findIndex(page=>page.id===id),previous=PORTAL_PAGES[index-1],next=PORTAL_PAGES[index+1],navigation=document.createElement('div');navigation.className='max-w-6xl mx-auto mb-8 flex items-center justify-between gap-4';navigation.innerHTML=`${previous?`<a href="${portalPageUrl(previous.id)}" class="inline-flex items-center gap-2 px-4 py-2 rounded-lg border border-white/10 bg-white/5 text-xs text-white/70 hover:bg-white/10 transition"><iconify-icon icon="lucide:arrow-left"></iconify-icon>${previous.label}</a>`:'<span></span>'}${next?`<a href="${portalPageUrl(next.id)}" class="inline-flex items-center gap-2 px-4 py-2 rounded-lg border border-white/10 bg-white/5 text-xs text-white/70 hover:bg-white/10 transition">${next.label}<iconify-icon icon="lucide:arrow-right"></iconify-icon></a>`:'<span></span>'}`;footer.prepend(navigation)}
function loadPortalEnhancement(source){return new Promise((resolve,reject)=>{const script=document.createElement('script');script.src=source;script.onload=resolve;script.onerror=reject;document.body.appendChild(script)})}
document.addEventListener('DOMContentLoaded',()=>{prepareDashboardSection();const id=getCurrentPortalPage();rewritePortalLinks();showCurrentPortalPage(id);buildPortalTopNavigation(id);addPageFooterNavigation(id);setTimeout(async()=>{await loadPortalEnhancement('team-branding.js');loadPortalEnhancement('auth-client.js');loadPortalEnhancement('featured-game.js');loadPortalEnhancement('live-stats.js');loadPortalEnhancement('tcu-live.js');loadPortalEnhancement('tcu-travel.js');loadPortalEnhancement('math-game.js');loadPortalEnhancement('student-dashboard.js')},0)});
