(() => {
  const main = document.querySelector('main');
  if (!main) return;
  const esc = value => String(value ?? '').replace(/[&<>"']/g, c => ({ '&':'&amp;', '<':'&lt;', '>':'&gt;', '"':'&quot;', "'":'&#39;' }[c]));
  const labels = { postgame:'Postgame Reporter', prediction:'Make Your Prediction', journal:'Season Journal' };
  const feedbackStarters = ['Great evidence. Next, explain why that detail matters.','Add one more football statistic to support your idea.','Check capitals and punctuation, then resubmit.','Make the opening sentence stronger so the reader knows your main idea.','Add a clear ending sentence that wraps up your thinking.'];
  const statusCopy = { submitted:{ label:'Waiting for feedback', classes:'text-red-200 border-red-400/30 bg-red-500/10' }, revision:{ label:'Returned for revision', classes:'text-amber-200 border-amber-400/35 bg-amber-500/10' }, complete:{ label:'Complete', classes:'text-green-200 border-green-400/35 bg-green-500/10' }, reviewed:{ label:'Complete', classes:'text-green-200 border-green-400/35 bg-green-500/10' } };
  const section = document.createElement('section');
  section.className = 'panel rounded-xl mt-6 overflow-hidden';
  section.dataset.teacherPage = 'writing';
  section.innerHTML = `<div class="p-5 border-b border-white/10 flex flex-col sm:flex-row sm:items-center justify-between gap-3"><div><h2 class="font-semibold">Writing Review Queue</h2><p class="text-xs text-white/35 mt-1">Choose a student submission to read, respond, and return.</p></div><div class="flex items-center gap-2"><div id="tw-summary" class="text-[10px] uppercase text-white/35 font-bold"></div><button id="tw-refresh" title="Refresh writing" class="w-9 h-9 rounded-lg bg-white/5"><iconify-icon icon="lucide:refresh-cw"></iconify-icon></button></div></div><div id="tw-list" class="p-5 grid sm:grid-cols-2 xl:grid-cols-3 gap-4"></div>`;
  main.appendChild(section);
  const modal = document.createElement('div');
  modal.id = 'tw-review-modal'; modal.className = 'fixed inset-0 z-50 hidden items-center justify-center p-4'; modal.style.cssText = 'background:rgba(0,0,0,.82);backdrop-filter:blur(8px)';
  modal.innerHTML = `<div class="panel rounded-2xl max-w-3xl w-full max-h-[90vh] overflow-y-auto relative"><button type="button" data-tw-close title="Close review" class="absolute top-4 right-4 w-9 h-9 rounded-lg bg-white/5 border border-white/10 grid place-items-center hover:bg-white/10"><iconify-icon icon="lucide:x"></iconify-icon></button><div id="tw-modal-content" class="p-6 md:p-8"></div></div>`;
  document.body.appendChild(modal);
  const closeModal = () => { modal.classList.add('hidden'); modal.classList.remove('flex'); };
  modal.addEventListener('click', event => { if (event.target === modal || event.target.closest('[data-tw-close]')) closeModal(); });
  function statusPill(status) { const item = statusCopy[status] || statusCopy.submitted; return `<span class="inline-flex items-center px-2 py-1 border rounded-full text-[10px] font-bold ${item.classes}">${item.label}</span>`; }
  function dateText(value) { return value ? new Date(value).toLocaleDateString(undefined, { month:'short', day:'numeric', year:'numeric' }) : 'Date unavailable'; }
  function checklistMarkup(row) { const checked = key => row.checklist?.[key] ? 'text-green-300' : 'text-white/25'; return `<div class="flex flex-wrap gap-2 text-[10px] uppercase font-bold"><span class="${checked('capitals')}">Capitals</span><span class="${checked('punctuation')}">Punctuation</span><span class="${checked('evidence')}">Evidence</span><span class="${checked('sentences')}">Complete sentences</span></div>`; }
  function renderModal(row) {
    const content = document.getElementById('tw-modal-content');
    content.innerHTML = `<div class="pr-8"><div class="flex flex-wrap items-center gap-2 text-[10px] uppercase font-bold"><span class="text-blue-300">${esc(labels[row.activity] || row.activity)}</span>${statusPill(row.status)}</div><h2 class="text-2xl font-black mt-3">${esc(row.display_name)}</h2><p class="text-xs text-white/45 mt-1">${esc(row.selected_team || 'Unassigned')} · Submitted ${dateText(row.submitted_at)}</p><h3 class="text-lg font-bold mt-6">${esc(row.title || 'Untitled')}</h3><div class="mt-3">${checklistMarkup(row)}</div><div class="mt-5 p-4 rounded-xl border border-white/10 bg-white/[.03] text-sm leading-7 text-white/75 whitespace-pre-wrap">${esc(row.content)}</div>${row.teacher_feedback ? `<div class="mt-4 p-4 rounded-xl border border-blue-400/20 bg-blue-500/[.06] text-sm text-white/65 whitespace-pre-wrap"><strong class="block text-xs uppercase tracking-wider text-blue-200 mb-2">Last feedback</strong>${esc(row.teacher_feedback)}</div>` : ''}<div class="mt-6 pt-5 border-t border-white/10"><label class="text-[10px] uppercase text-white/40 font-bold">Teacher Feedback<textarea id="tw-feedback-${row.id}" class="mt-3 w-full min-h-[140px] bg-white/5 border border-white/10 rounded-xl p-3 text-sm outline-none focus:border-blue-400" placeholder="Add encouragement and one clear next step...">${esc(row.teacher_feedback || '')}</textarea></label><div class="mt-3 flex flex-wrap gap-2">${feedbackStarters.map(text => `<button type="button" data-feedback-chip="${row.id}" data-feedback-text="${esc(text)}" class="px-2.5 py-1.5 rounded-lg border border-white/10 bg-white/5 hover:bg-white/10 text-[10px] text-white/60">${esc(text.split('.')[0])}</button>`).join('')}</div><div class="mt-5 grid sm:grid-cols-2 gap-2"><button type="button" data-review-revision="${row.id}" class="w-full bg-amber-500 hover:bg-amber-400 text-black rounded-lg py-3 text-xs font-black">Return for Revision</button><button type="button" data-review-complete="${row.id}" class="w-full bg-green-700 hover:bg-green-600 rounded-lg py-3 text-xs font-semibold">Mark Complete</button></div></div></div>`;
    content.querySelectorAll('[data-feedback-chip]').forEach(button => button.onclick = () => { const textarea = document.getElementById(`tw-feedback-${button.dataset.feedbackChip}`); textarea.value = `${textarea.value.trim()}${textarea.value.trim() ? '\n' : ''}${button.dataset.feedbackText}`; textarea.focus(); });
    content.querySelector('[data-review-revision]')?.addEventListener('click', event => sendReview(row.id, 'revision', event.currentTarget));
    content.querySelector('[data-review-complete]')?.addEventListener('click', event => sendReview(row.id, 'complete', event.currentTarget));
  }
  function openReview(row) { if (!row) return; renderModal(row); modal.classList.remove('hidden'); modal.classList.add('flex'); }
  async function sendReview(id, status, button) { button.disabled = true; try { const feedback = document.getElementById(`tw-feedback-${id}`).value; await api(`/api/teacher/writing/${id}`, { method:'PATCH', body:JSON.stringify({ feedback, status }) }); closeModal(); window.refreshTeacherNotifications?.(); await load(); } catch (error) { button.disabled = false; alert(error.message); } }
  function renderRows(rows) {
    const pending = rows.filter(row => row.status === 'submitted').length, returned = rows.filter(row => row.status === 'revision').length, complete = rows.filter(row => row.status === 'complete' || row.status === 'reviewed').length;
    document.getElementById('tw-summary').textContent = `${pending} waiting · ${returned} revising · ${complete} complete`;
    document.getElementById('tw-list').innerHTML = rows.length ? rows.map(row => { const dimmed = row.status === 'complete' || row.status === 'reviewed'; return `<button type="button" data-writing-id="${row.id}" class="text-left group panel rounded-xl p-4 border border-white/10 hover:border-blue-400/50 hover:bg-blue-500/[.05] transition ${dimmed ? 'opacity-70' : ''}"><div class="flex items-start justify-between gap-3"><div class="min-w-0"><div class="text-[10px] uppercase tracking-wider font-bold text-blue-300">${esc(labels[row.activity] || row.activity)}</div><h3 class="mt-2 text-base font-black truncate">${esc(row.display_name)}</h3></div>${statusPill(row.status)}</div><p class="mt-3 text-sm font-semibold text-white/75 truncate">${esc(row.title || 'Untitled')}</p><p class="mt-2 text-[11px] text-white/40 line-clamp-2">${esc(row.content || 'No writing content yet.')}</p><div class="mt-4 flex items-center justify-between text-[10px] text-white/35"><span>${esc(row.selected_team || 'Unassigned')}</span><span>${dateText(row.submitted_at)}</span></div><span class="mt-4 inline-flex items-center gap-1 text-[10px] font-bold uppercase tracking-wider text-blue-300">Open submission <iconify-icon icon="lucide:arrow-up-right"></iconify-icon></span></button>`; }).join('') : '<div class="sm:col-span-2 xl:col-span-3 p-10 text-center text-sm text-white/35">No writing submissions yet.</div>';
    document.querySelectorAll('[data-writing-id]').forEach(button => button.onclick = () => openReview(rows.find(row => String(row.id) === button.dataset.writingId)));
    window.refreshTeacherNotifications?.();
  }
  async function load() { const data = await api('/api/teacher/writing'); const rows = data.submissions || []; renderRows([...rows.filter(row => row.status === 'submitted'), ...rows.filter(row => row.status === 'revision'), ...rows.filter(row => row.status === 'complete' || row.status === 'reviewed')]); }
  document.getElementById('tw-refresh').onclick = load;
  load().catch(error => { document.getElementById('tw-list').innerHTML = `<div class="sm:col-span-2 xl:col-span-3 p-8 text-red-300 text-sm">${esc(error.message)}</div>`; });
})();
