(() => {
  const section=document.getElementById('writing');if(!section)return;
  const activities={postgame:{label:'Postgame Reporter',icon:'newspaper',xp:50,goal:120,prompt:'Explain what happened in your team’s latest game. Include the final score, an important play, and evidence from a statistic.',starters:['The most important moment of the game was...','One statistic that explains the result is...','My team can improve by...']},prediction:{label:'Make Your Prediction',icon:'chart-no-axes-combined',xp:40,goal:100,prompt:'Predict your team’s next game. Use at least one statistic as evidence, then explain what you will check after the game.',starters:['I predict that my team will...','The strongest evidence for my prediction is...','After the game, I will check...']},journal:{label:'Season Journal',icon:'book-open',xp:30,goal:80,prompt:'Record an important moment from your team’s season and explain why it matters.',starters:['This week, my team...','This moment matters because...','My biggest question now is...']}};
  const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const api=async(url,options={})=>{const response=await fetch(url,{headers:{'Content-Type':'application/json'},...options}),data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.error||'The Press Room could not load.');return data};
  let state={activity:'postgame',entries:[],profile:null,team:'your team'};
  section.innerHTML=`<div class="max-w-6xl mx-auto px-4 md:px-6"><div class="border-y border-white/10 py-7 mb-6 flex flex-col md:flex-row md:items-end justify-between gap-4"><div><div class="text-[10px] uppercase tracking-[.2em] text-brand-400 font-bold">NFL Press Room</div><h1 class="text-3xl md:text-4xl font-black mt-2">Tell the story of your season</h1><p class="text-sm text-white/45 mt-2">Research, draft, revise, and submit writing about <span id="wl-team">your team</span>.</p></div><div class="flex gap-px bg-white/10 border border-white/10"><div class="bg-[#111] px-5 py-3"><div class="text-[9px] uppercase text-white/35">Writing XP</div><div id="wl-xp" class="text-xl font-black">0</div></div><div class="bg-[#111] px-5 py-3"><div class="text-[9px] uppercase text-white/35">Submitted</div><div id="wl-submissions" class="text-xl font-black">0</div></div></div></div><div id="wl-activities" class="grid md:grid-cols-3 gap-3 mb-6"></div><div class="grid lg:grid-cols-[1.45fr_.55fr] gap-6"><div class="border border-white/10"><div class="p-5 border-b border-white/10"><div id="wl-activity-label" class="text-[10px] uppercase text-brand-400 font-bold"></div><input id="wl-title" maxlength="120" placeholder="Add a headline or title" class="mt-3 w-full bg-transparent text-2xl font-black outline-none placeholder:text-white/20"><p id="wl-prompt" class="mt-3 text-sm text-white/55 leading-relaxed"></p><div id="wl-starters" class="flex flex-wrap gap-2 mt-4"></div></div><div class="p-5"><textarea id="wl-content" maxlength="12000" class="w-full min-h-[330px] resize-y bg-black/25 border border-white/10 p-4 text-sm leading-7 outline-none focus:border-brand-400" placeholder="Start writing here..."></textarea><div class="mt-3 flex items-center gap-3"><div class="h-2 flex-1 bg-white/5 overflow-hidden"><div id="wl-progress" class="h-full bg-brand-500 transition-all"></div></div><span id="wl-count" class="text-[10px] text-white/40 min-w-[90px] text-right">0 words</span></div></div><div class="p-5 border-t border-white/10"><div class="text-[10px] uppercase text-white/35 font-bold mb-3">Reporter’s Checklist</div><div id="wl-checklist" class="grid sm:grid-cols-2 gap-3"></div><div id="wl-message" class="hidden mt-4 p-3 text-xs border"></div><div class="flex flex-wrap gap-2 mt-5"><button id="wl-save" class="px-5 py-3 border border-white/15 hover:bg-white/5 text-xs font-bold">Save Draft</button><button id="wl-submit" class="px-5 py-3 bg-brand-500 hover:bg-brand-400 text-xs font-bold">Submit to Teacher</button></div></div></div><aside class="space-y-6"><div class="border border-white/10"><div class="p-4 border-b border-white/10"><h2 class="font-bold">My Press Box</h2></div><div id="wl-history"></div></div><div class="border border-white/10"><div class="p-4 border-b border-white/10"><h2 class="font-bold">Writing Leaders</h2></div><div id="wl-leaders"></div></div></aside></div></div>`;
  const $=id=>document.getElementById(id),words=()=>$('wl-content').value.trim().split(/\s+/).filter(Boolean).length;
  function checklist(){return Object.fromEntries([...document.querySelectorAll('[data-check]')].map(input=>[input.dataset.check,input.checked]))}
  function renderActivities(){ $('wl-activities').innerHTML=Object.entries(activities).map(([key,a])=>`<button data-activity="${key}" class="text-left p-5 border ${key===state.activity?'border-brand-400 bg-brand-500/10':'border-white/10 hover:bg-white/[.03]'}"><div class="flex items-center justify-between"><iconify-icon icon="lucide:${a.icon}" class="text-xl text-brand-400"></iconify-icon><span class="text-[10px] font-bold text-white/40">+${a.xp} XP</span></div><div class="font-bold mt-4">${a.label}</div><div class="text-[10px] text-white/35 mt-1">Goal: ${a.goal} words</div></button>`).join('');document.querySelectorAll('[data-activity]').forEach(button=>button.onclick=()=>selectActivity(button.dataset.activity)) }
  function renderChecklist(entry={}){const checks=[['capitals','I checked capitals'],['punctuation','I checked punctuation'],['evidence','I used facts or statistics'],['sentences','I wrote complete sentences']];$('wl-checklist').innerHTML=checks.map(([key,label])=>`<label class="flex items-center gap-3 text-xs text-white/65"><input data-check="${key}" type="checkbox" ${entry.checklist?.[key]?'checked':''} class="accent-blue-500">${label}</label>`).join('')}
  function selectActivity(key){state.activity=key;const a=activities[key],entry=state.entries.find(item=>item.activity===key)||{};$('wl-activity-label').textContent=a.label;$('wl-prompt').textContent=a.prompt.replace('your team',state.team);$('wl-title').value=entry.title||'';$('wl-content').value=entry.content||'';$('wl-starters').innerHTML=a.starters.map(text=>`<button class="px-3 py-2 border border-white/10 text-[10px] text-white/55 hover:text-white hover:bg-white/5">${esc(text)}</button>`).join('');[...$('wl-starters').children].forEach((button,index)=>button.onclick=()=>{const starter=a.starters[index];$('wl-content').value+=`${$('wl-content').value.trim()?'\n\n':''}${starter} `;updateCount();$('wl-content').focus()});renderChecklist(entry);renderActivities();updateCount();showMessage(entry.teacher_feedback?`Teacher feedback: ${entry.teacher_feedback}`:'',entry.teacher_feedback?'success':'')}
  function updateCount(){const count=words(),goal=activities[state.activity].goal;$('wl-count').textContent=`${count} / ${goal} words`;$('wl-progress').style.width=`${Math.min(100,count/goal*100)}%`}
  function showMessage(text,type='success'){const el=$('wl-message');if(!text){el.classList.add('hidden');return}el.textContent=text;el.className=`mt-4 p-3 text-xs border ${type==='error'?'border-red-500/30 bg-red-500/10 text-red-200':'border-green-500/30 bg-green-500/10 text-green-200'}`}
  function renderProfile(data){state.profile=data;$('wl-xp').textContent=Number(data.writingXp||0).toLocaleString();$('wl-submissions').textContent=data.submissions||0;$('wl-history').innerHTML=state.entries.length?state.entries.map(entry=>`<button data-open="${entry.activity}" class="w-full text-left p-4 border-b border-white/5 hover:bg-white/[.03]"><div class="flex justify-between gap-2"><span class="text-xs font-bold">${esc(activities[entry.activity]?.label||entry.activity)}</span><span class="text-[9px] uppercase text-brand-400">${esc(entry.status)}</span></div><div class="text-[10px] text-white/35 mt-1 truncate">${esc(entry.title||'Untitled draft')}</div>${entry.teacher_feedback?`<div class="text-[10px] text-green-300 mt-2">Feedback ready</div>`:''}</button>`).join(''):'<div class="p-6 text-center text-xs text-white/35">Your saved writing will appear here.</div>';document.querySelectorAll('[data-open]').forEach(button=>button.onclick=()=>selectActivity(button.dataset.open));$('wl-leaders').innerHTML=data.leaderboard?.length?data.leaderboard.slice(0,5).map((row,index)=>`<div class="grid grid-cols-[24px_1fr_auto] gap-2 p-3 border-b border-white/5 text-xs"><span class="text-white/30 font-black">${index+1}</span><span class="truncate">${esc(row.display_name)}</span><span class="font-black">${row.writing_xp} XP</span></div>`).join(''):'<div class="p-6 text-center text-xs text-white/35">No submissions yet.</div>'}
  async function save(submit=false){const payload={activity:state.activity,title:$('wl-title').value,content:$('wl-content').value,checklist:checklist()};try{const data=await api(submit?'/api/writing/submit':'/api/writing/save',{method:'POST',body:JSON.stringify(payload)});showMessage(data.message);await load()}catch(error){showMessage(error.message,'error')}}
  async function load(){const [me,data]=await Promise.all([api('/api/me'),api('/api/writing/profile')]);state.team=typeof getNFLTeamBrand==='function'?(getNFLTeamBrand(me.user.selectedTeam)?.name||'your team'):'your team';state.entries=data.entries||[];$('wl-team').textContent=state.team;renderProfile(data);selectActivity(state.activity)}
  $('wl-content').addEventListener('input',updateCount);$('wl-save').onclick=()=>save(false);$('wl-submit').onclick=()=>save(true);load().catch(error=>showMessage(error.message,'error'));
})();
